### PR TITLE
fix python setup.py bdist_rpm

### PR DESCRIPTION
**Pull request by ghost**
metadata.json has a problem when building (rpm-)packages. It doesn't gets copied to the parent directory of yumutils but to /usr.
version.py can't find metadata.json theirfor for rpm builds and regular installations.
i thought it would be better to put metadata into a .py-file and include it into setup.py instead which should work for all install cases.
that is the patch for that. it works for me.

### CODE REVIEW

**Comment by jrwesolo** [comment]
@hoonetorg Thanks for your thoughts on this! I am admittedly a bit fuzzy on the packaging mechanics. I mainly package this into a docker image and use it that way. I'm going to explore the rpm issue a bit and your solution. The main reason for the metadata.json is that it was easy to hook into some existing CI/CD pipelines that I built that use the json for some checks. I'm open to changing that if it make the rpm builds work. I'll let you know!

**Comment by jrwesolo** [comment]
@hoonetorg I'm going to merge this into the develop branch and make some modifications. I'll see about getting out a new version today! Thank you.

**Comment by hoonetorg** [comment]
@jrwesolo thx

**Comment by jrwesolo** [comment]
@hoonetorg Your changes have been merged in and released in v1.1.1. I made a couple modifications in https://github.com/jrwesolo/yumsync/pull/20/commits/c93516df0fcc972725a0243d4cf4c58995db1477. As I was reading documentation and seeing what files were actually added to a package, the package_data wasn't actually doing what I was expecting. I tested all the changes with bdist_wheel and bdist_rpm successfully.

**Comment by hoonetorg** [comment]
@jrwesolo thx, this works for me 
currently i build the package with 
```python setup.py bdist_rpm --requires PyYAML,python-blessings,pyliblzma,createrepo```
keeping setup.cfg from this PR would make option ```--requires ...``` unnecessary.

**Comment by jrwesolo** [comment]
@hoonetorg what version of Python are you using to do the builds?

**Comment by hoonetorg** [comment]
currently still plain centos 7.2 python (python-2.7.5-39.el7_2.x86_64)
7.3 coming soon

**Comment by jrwesolo** [comment]
I tested building and installing the rpms and confirmed the issue you are seeing. I'll add the setup.cfg back in the next release.

**Comment by jrwesolo** [comment]
This has been fixed in v1.2.0.

**Pull request merged**
